project_name: eks-node-explorer

source:
  enabled: false

before:
  hooks:
    - go mod download

builds:
  - binary: eks-node-explorer
    main: ./cmd/eks-node-explorer
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -v

universal_binaries:
 - replace: true

archives:
  - id: eks-node-explorer
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format: binary

release:
  prerelease: auto

snapshot:
  name_template: "{{ .Tag }}-next"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha256_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  skip: false
  use: git # github(-native)
  filters:
    exclude:
    - '^docs:'
    - '^test:'
